### ISSUE TITLE
How to obtain ZenTuner

### ISSUE THREAD

**Issue by carlca** [jpsim/ZenTuner#18]
I'm assuming that there is a macOS version of this app. However, it doesn't seem to be available on the App Store from the UK. I'm quite comfortable cloning it in Git and building from source, but I cannot see any build instructions. Can you help? Thanks!

**Comment by jpsim** [comment]
I _think_ Zen Tuner builds and works on macOS 11, but I don't have access to a computer running that version of macOS. My main and only machine is still running macOS 10.15 Catalina.

If you want to try it out, although like I said it might not work, here are the build and run instructions:

1. Download the latest version of Xcode: https://developer.apple.com/xcode/
2. Clone this git repository: `git clone https://github.com/jpsim/ZenTuner.git`
3. `cd ZenTuner`
4. `xed .`
5. Select the `ZenTuner_macOS` scheme in Xcode
6. Select "My Mac" as a run target
7. Hit cmd-R to run

You'll probably need to adjust code signing settings to code sign the app yourself.

**Comment by carlca** [comment]
Thanks! I have macOS 10.14.6 Mojave. Are you saying that it won't build on that version?
Also, for disk space reasons, I deleted the full version of Xcode. Is there any way of building from the command-line?
Alternatively, any idea why I can't download it from the App Store?
Sorry to bombard you with questions 😉

**Comment by jpsim** [comment]
> Are you saying that it won't build on that version?

You can build on any macOS version that supports Xcode 12. It won't run on any version of macOS prior to macOS 11 though.

> Also, for disk space reasons, I deleted the full version of Xcode. Is there any way of building from the command-line?

The app can be built with `xcodebuild` from the command line, but that requires the full version of Xcode to be installed, so it doesn't help your case.

> Alternatively, any idea why I can't download it from the App Store?

It would be foolish of me to publish an app that I've never tested 🙃 

> Sorry to bombard you with questions 😉

No problem!

---

FYI for the time being, Zen Tuner works well on iOS & iPadOS, you can download it here: https://apps.apple.com/us/app/zen-tuner/id1550640624

**Comment by carlca** [comment]
I've just downloaded on my iPad and it seems to be working perfectly - I do keep forgetting that my iPad has a perfectly good microphone built in, so this will work very nicely for me 😀
Thanks a lot, JP!

**Comment by jpsim** [comment]
Zen Tuner is now on the Mac App Store: https://apps.apple.com/us/app/zen-tuner/id1550640624

**Comment by carlca** [comment]
Thanks JP. Seems like I still have to wait for Big Sur. The Mac App Store
is still blocking my macOS 10.14.6!


On 17 June 2021 at 15:12:01, JP Simard ***@***.***) wrote:

Zen Tuner is now on the Mac App Store:
https://apps.apple.com/us/app/zen-tuner/id1550640624

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jpsim/ZenTuner/issues/18#issuecomment-863274333>, or
unsubscribe

**Comment by jpsim** [comment]
Correct, you need macOS 11 or iOS 14 to run Zen Tuner.
