### ISSUE TITLE
Could there be a macos build?

### ISSUE THREAD

**Issue by chetanpm** [jpsim/ZenTuner#21]
Since there are so many apps using translations between ipad touch to macos trackpad, could this be built for x86_mac or universal binaries which includes the ARM macs too?

**Comment by jpsim** [comment]
I tried the macOS version for the first time a few days ago and it works, but I’m not sure how compelling it is as a Mac app.

**Comment by chetanpm** [comment]
Well, there are apps that do the job. I thought it is worth releasing an open license minimalistic(zen) app and it can eventually be turned to live in the menubar with enough interest by other people.

**Comment by jpsim** [comment]
I'll consider doing this. In the meantime you should be able to build and install from source.

**Comment by jpsim** [comment]
Zen Tuner is now on the Mac App Store: https://apps.apple.com/us/app/zen-tuner/id1550640624
