### ISSUE TITLE
Smooth indicator movement

### ISSUE THREAD

**Issue by daneal** [jpsim/ZenTuner#40]
Is there a way to apply a "smoothing" factor to cause the note indicator to not jump around so much and just ease slowly into a new position?

**Comment by jpsim** [comment]
Well the not indicator does smoothly animate when moving, but I think you're asking how to make that animation even slower?

You can adjust the animation speed by specifying a duration here: https://github.com/jpsim/ZenTuner/blob/e75288da2bc0759f308cb49bf9e05a90870f9066/ZenTuner/Views/CurrentNoteMarker.swift#L27

For example:

```swift
.animation(.easeInOut(duration: 1), value: distance.cents)
```

If you're asking for me to expose a way to expose the animation speed in the UI to enable users to control it, I'll have to give this more serious thought. A main goal of this app is to be minimalist (ahem "zen") so naturally this means not having too many fiddly knobs and controls.

**Comment by daneal** [comment]
I am more asking if there is a way to smooth the frequency that comes from the microphone. For example, a very simple data smoothing algorithm would take each new measurement that comes from the microphone and weight it at 10% while weighting the previous frequency at 90% 
`smoothedFrequency = (newFrequency * 0.1) + (oldFrequency * 0.0)'

**Comment by jpsim** [comment]
Sure, you could do that here https://github.com/jpsim/ZenTuner/blob/e75288da2bc0759f308cb49bf9e05a90870f9066/Packages/MicrophonePitchDetector/Sources/MicrophonePitchDetector/MicrophonePitchDetector.swift#L76

But I'd still recommend adjusting the animation speed.

**Comment by daneal** [comment]
Thank you, I will experiment with both approaches. And thank you for creating ZenTuner. It has been a huge help!
